name: CI

on:   # which events trigger the workflow ,here we trigger on push and pull request to main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: # what to do in this workflow 
  test:
    runs-on: ubuntu-latest # GitHub creates a temporary Linux machine.
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Downloads your GitHub repo into the CI machine.

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up uv
        uses: astral-sh/setup-uv@v4

      - name: Sync dependencies with uv (locked)
        run: |
          uv sync --frozen
          uv pip install pytest
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/multi_doc_chat
          GROQ_API_KEY: dummy
          GOOGLE_API_KEY: dummy
          LLM_PROVIDER: google
        run: |
          uv run pytest -q

          